#!/usr/bin/env bash
# script that transfers a file from our client to a server
i=0;
for arguments in "$@"
do
	i=$((i + 1))
done

if [ "$i" -lt "4" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
