#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect requirements
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
touch /var/www/html/index.html
chmod 666 /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
