#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect requirements
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
