#!/usr/bin/env bash
# script that configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 666 etc/nginx/sites-available/default
sudo sed -i '/server_name _;/ a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;' /etc/nginx/sites-available/backup_default2
