#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm var/run/holbertonscript.pid" SIGQUIT exit
while :
do
  echo To infinity and beyond
  sleep 2
done
