#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with a condition
n=1

while [ $n -le 100 ]
do
	if  [[ 0 -eq "($n%15)" ]]
	then
		echo "FizzBuzz"
	elif  [[ 0 -eq "($n%5)" ]]
	then
		echo "Fizz"
	elif  [[ 0 -eq "($n%3)" ]]
	then
		echo "Buzz"
	else
		echo "$n"
	fi
	n=$(( n+1 ))
done
