#!/usr/bin/env bash
# This script taht displays numbers from 1 to 100.
n=1

while [ $n -le 100 ]
do
	if  [[ 0 -eq $((n%15)) ]]
	then
		echo "FizzBuzz"
	elif  [[ 0 -eq $((n%5)) ]]
	then
		echo "Buzz"
	elif  [[ 0 -eq $((n%3)) ]]
	then
		echo "Fizz"
	else
		echo "$n"
	fi
	n=$(( n+1 ))
done
