#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with a condition
n=1

while [ "$n" -le 10 ]
do
	if [ "$n" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	n=$(( n+1 ))
done
