#!/usr/bin/env bash
# Bash script that configures the container to make nginx listen on all active IPs on port 8080
pkill -9 apache2
sed -i '21,22 s/80/8080/g' /etc/nginx/sites-available/default
chmod ugo+wr /etc/nginx/nginx.conf
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx nginx
